// ui/src/pages/HomePage.tsx
import React from 'react';
import { Navigate, useLocation, Link } from 'react-router-dom';
import useAuth from '@/hooks/useAuth';

import LoadingSpinner from '@/components/LoadingSpinner';

import '@/assets/style/AuthForm.css';

const HomePage: React.FC = () => {
  const { authenticated, isLoading } = useAuth();
  const location = useLocation();

  if (isLoading) {
    return <LoadingSpinner />;
  }

  if (authenticated) {
    return <Navigate to="/dashboard" state={{ from: location }} replace />;
  }

  return (
    <div className="auth-container">
      <h1>Horus Holdings</h1>
      <div className="auth-links">
        <Link to="/login" className="btn text-bold">Login</Link>
        <Link to="/register" className="btn text-bold">Register</Link>
      </div>
    </div>
  );
};

export default HomePage;

// ui/src/pages/public/HomePage.vue
<script setup lang="ts">
import { useRouter, RouterLink } from 'vue-router'

import { useAuthStore } from '@/stores/auth';

const { isLoading, authenticated } = useAuthStore();
const router = useRouter();

if (!isLoading && authenticated) {
  router.push({ name: 'dashboard' });
}
</script>

<template>
  <div className="auth-container">
    <div v-if="isLoading">
      <KSkeleton type="form" />;
    </div>

    <div v-else class="auth-links">
      <h1>Horus Holdings</h1>
      <RouterLink class="btn text-bold" to="/login">Login</RouterLink>
      <RouterLink class="btn text-bold" to="/register">Register</RouterLink>
    </div>
  </div>
</template>
