// src/pages/NotFound.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';

import useAuth from '../hooks/useAuth';

import '../assets/style/NotFound.css';

const NotFound: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useAuth();

  const handleBackHome = () => {
    if ( user ) {
      return navigate('/dashboard');
    }

    navigate('/');
  };

  return (
    <div className="not-found-container">
      <h1 className="text-bold mb-5">404</h1>
      <h2 className="mb-10">The page you visited does not exist.</h2>
      <button onClick={handleBackHome} className="btn text-bold">
        Go Home
      </button>
    </div>
  );
};

export default NotFound;

// ui/src/pages/public/NotFound.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';
</script>

<template>
  <div className="not-found-container">
    <h1 className="text-bold mb-5">404</h1>
    <h2 className="mb-10">The page you visited does not exist.</h2>
    <RouterLink class="btn text-bold" to="/dashboard">Go home</RouterLink>
  </div>
</template>

<style>
.not-found-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
}
</style>
