// ui/src/components/FinancialForm.vue
<script setup lang="ts">
import type {
  FinanceItemKind,
  FinancialItem,
  RecurrencePayload,
  RecurrenceKind,
} from "@/types";

import { ref, watch, computed, onBeforeUnmount } from "vue";
import dayjs from "dayjs";
import axios from "axios";

import { ToastManager } from '@kong/kongponents'
import { useThemeStore } from '@/stores/theme'
import { getServiceConfig } from "@/utils/service";

import RecurrenceBuilder from "@/components/RecurrenceBuilder/RecurrenceBuilder.vue";

type Kind = FinanceItemKind;

const props = defineProps<{
  kind: Kind;
  visible: boolean;
  itemToUpdate?: FinancialItem | null;
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "saved"): void;
}>();

const { apiUrl } = getServiceConfig();
const themeStore = useThemeStore();
const toaster = new ToastManager();

const isEdit = computed(() => !!props.itemToUpdate?.id);
const kindLabel = computed(() => props.kind === "income" ? "Income" : "Expense");

type FormModel = {
  name: string;
  amount: number;
  category?: string;
};
const form = ref<FormModel>({
  name: "",
  amount: 0,
  category: undefined,
});

const recurrence = ref<RecurrencePayload>({
  recurrenceKind: "none",
  anchorDate: dayjs().format("YYYY-MM-DD"),
  endDate: undefined,
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "America/New_York",
  weekendAdjustment: "none",
  includeDates: undefined,
  excludeDates: undefined,
  simple: undefined,
  rrule: undefined,
});

const submitting = ref(false);

onBeforeUnmount(() => {
  toaster.destroy();
});

const canSubmit = computed(() => {
  return !!form.value.name && !!form.value.amount
})

function resetFromItem() {
  const it = props.itemToUpdate;

  form.value = {
    name: it?.name ?? "",
    amount: it?.amount ?? 0,
    category: it?.category,
  };

  const kind: RecurrenceKind = it?.recurrenceKind ?? "none";

  if (kind === "none") {
    const d = it?.date || dayjs().format("YYYY-MM-DD");

    recurrence.value = {
      recurrenceKind: "none",
      anchorDate: d, // one-time uses date=anchor
      endDate: it?.endDate,
      timezone: it?.timezone || recurrence.value.timezone,
      weekendAdjustment: it?.weekendAdjustment || "none",
      includeDates: it?.includeDates,
      excludeDates: it?.excludeDates,
    };
  } else if (kind === "simple") {
    recurrence.value = {
      recurrenceKind: "simple",
      anchorDate: it?.anchorDate || dayjs().format("YYYY-MM-DD"),
      endDate: it?.endDate,
      timezone: it?.timezone || recurrence.value.timezone,
      weekendAdjustment: it?.weekendAdjustment || "none",
      includeDates: it?.includeDates,
      excludeDates: it?.excludeDates,
      simple: it?.simple ?? { type: "weekly", interval: 1, daysOfWeek: [] },
      rrule: undefined,
      count: it?.count,
    };
  } else {
    // rrule
    recurrence.value = {
      recurrenceKind: "rrule",
      anchorDate: it?.anchorDate || dayjs().format("YYYY-MM-DD"),
      endDate: it?.endDate,
      timezone: it?.timezone || recurrence.value.timezone,
      weekendAdjustment: it?.weekendAdjustment || "none",
      includeDates: it?.includeDates,
      excludeDates: it?.excludeDates,
      simple: undefined,
      rrule: it?.rrule || "",
      count: it?.count,
    };
  }
}

watch(
  () => [props.visible, props.itemToUpdate],
  () => {
    if (props.visible) {
      resetFromItem();
    }
  },
  { immediate: true }
);

function onClose() {
  emit("close");
}

function buildPayload() {
  const base = {
    name: form.value.name,
    amount: form.value.amount ?? 0,
    category: form.value.category,
  };

  if (recurrence.value.recurrenceKind === "none") {
    const anchorDate = recurrence.value.anchorDate; // One-off uses anchor as the date

    return {
      ...base,
      date: anchorDate,
      recurrence: {
        ...recurrence.value,
        simple: undefined,
        rrule: undefined,
        count: recurrence.value.count,
      },
    };
  }

  // 'simple' or 'rrule'
  return {
    ...base,
    recurrence: {
      ...recurrence.value,
    },
  };
}

async function onSubmit() {
  if (!canSubmit.value) {
    toaster.open({
      title: 'Missing information',
      message: 'Please enter a name and amount before saving.',
      appearance: 'danger'
    });

    return;
  }

  try {
    submitting.value = true;
    const payload = buildPayload();

    if (isEdit.value && props.itemToUpdate?.id) {
      await axios.put(
        `${apiUrl}/${props.kind}/${props.itemToUpdate.id}`,
        payload
      );
      toaster.open({
        title: `${kindLabel.value} updated`,
        appearance: 'success'
      });
    } else {
      await axios.post(`${apiUrl}/${props.kind}`, payload);
      toaster.open({
        title: `${kindLabel.value} created`,
        appearance: 'success'
      });
    }

    emit("saved");
    onClose();
  } catch (e: any) {
    const msg = e?.response?.data?.error || e?.message || "Request failed";

    toaster.open({
      title: 'Error',
      message: msg,
      appearance: 'danger'
    });
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <KModal
    :visible="visible"
    :title="isEdit ? 'Edit ' + kindLabel : 'Add ' + kindLabel"
    :action-button-text="isEdit ? 'Save' : 'Create'"
    :action-button-disabled="submitting || !canSubmit"
    :style="themeStore.isDark ? { '--kui-color-background-neutral-weakest': 'var(--background-secondary)' } : {}"
    @proceed="onSubmit"
    @cancel="onClose"
  >
    <div class="flex flex-col gap-6">
      <div class="flex flex-col gap-2">
        <KInput
          id="finance-name"
          v-model="form.name"
          label="Name"
          placeholder="e.g., Paycheck, Groceries"
          required
        />
      </div>

      <div class="flex flex-col gap-2">
        <KInput
          id="finance-amount"
          v-model.number="form.amount"
          label="Amount"
          type="number"
          min="0.01"
          step="0.01"
          placeholder="0.00"
          required
        />
      </div>

      <div class="flex flex-col gap-2">
        <KInput
          id="finance-category"
          v-model="form.category"
          label="Category"
          placeholder="Optional (e.g., Rent, Food)"
        />
      </div>

      <hr class="border-t border-gray-200 dark:border-gray-700" />

      <RecurrenceBuilder v-model="recurrence" />
    </div>
  </KModal>
</template>

// ui/src/components/FinancialForm.tsx
import type { FinancialItem, RecurrencePayload } from '@/types';

import React, { useState, useEffect } from 'react';
import axios from 'axios';
import {
  Modal,
  Checkbox,
  Form,
  Input,
  InputNumber,
  DatePicker,
  Select,
  Space,
  message,
} from 'antd';
import dayjs from 'dayjs';

import { useTheme, THEME } from '@/context/ThemeContext';

import RecurrenceBuilder from '@/components/RecurrenceBuilder';

type ItemKind = 'income' | 'expense';

interface FinancialFormProps {
  apiUrl: string;
  visible: boolean;
  onClose: () => void;
  itemToUpdate?: FinancialItem;
  kind: ItemKind;
  additionalFields?: React.JSX.Element;
}

const FinancialForm: React.FC<FinancialFormProps> = ({
  apiUrl, visible, onClose, itemToUpdate, kind, additionalFields
}) => {
  const { currentTheme } = useTheme();

  const colors = {
    backgroundColor: currentTheme === THEME.LIGHT ? '#CFC5BF' : '#594a4e',
    color:           currentTheme === THEME.LIGHT ? '#33272a' : '#fffffe',
  };

  const modalStyles = {
    header:  { backgroundColor: colors.backgroundColor },
    body:    { backgroundColor: colors.backgroundColor },
    content: { backgroundColor: colors.backgroundColor },
  };

  const isUpdate = Boolean(itemToUpdate?.id);
  const [recurring, setRecurring] = useState(false);

  const [form] = Form.useForm();

  const [recurrence, setRecurrence] = useState<RecurrencePayload>({
    recurrenceKind:    'none',
    anchorDate:        dayjs().format('YYYY-MM-DD'),
    timezone:          Intl.DateTimeFormat().resolvedOptions().timeZone,
    weekendAdjustment: 'none',
    includeDates:      [],
    excludeDates:      [],
  });

  useEffect(() => {
    if (isUpdate && itemToUpdate) {
      form.setFieldsValue({
        description: itemToUpdate.description,
        amount:      itemToUpdate.amount,
        category:    itemToUpdate.category || undefined,
        date:        itemToUpdate.date ? dayjs(itemToUpdate.date) : undefined,
      });
      setRecurrence({
        recurrenceKind:    itemToUpdate.recurrenceKind || 'none',
        rrule:             itemToUpdate.rrule || undefined,
        anchorDate:        itemToUpdate.anchorDate || dayjs().format('YYYY-MM-DD'),
        endDate:           itemToUpdate.endDate || null,
        count:             itemToUpdate.count || null,
        timezone:          itemToUpdate.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone,
        weekendAdjustment: itemToUpdate.weekendAdjustment || 'none',
        includeDates:      itemToUpdate.includeDates || [],
        excludeDates:      itemToUpdate.excludeDates || [],
      });
    } else {
      form.resetFields();
      setRecurrence({
        recurrenceKind:    'none',
        anchorDate:        dayjs().format('YYYY-MM-DD'),
        timezone:          Intl.DateTimeFormat().resolvedOptions().timeZone,
        weekendAdjustment: 'none',
        includeDates:      [],
        excludeDates:      [],
      });
    }
  }, [isUpdate, itemToUpdate, form]);

  async function handleSubmit() {
    const values = await form.validateFields();
    const payload = {
      description: values.description,
      amount:      Number(values.amount),
      category:    values.category || null,
      date:        values.date ? values.date.format('YYYY-MM-DD') : null,
      recurrence,
    };

    try {
      if (isUpdate) {
        const id = itemToUpdate?.id;

        if (kind === 'income') {
          await axios.put(`${ apiUrl }/income/${ id }`, payload);
        } else {
          await axios.put(`${ apiUrl }/expense/${ id }`, payload);
        }

        message.success('Updated successfully');
      } else {
        if (kind === 'income') {
          await axios.post(`${ apiUrl }/income`, payload);
        } else {
          await axios.post(`${ apiUrl }/expense`, payload);
        }

        message.success('Created successfully');
      }

      onClose();
    } catch (error: any) {
      console.warn('Save failed: ', error);

      if (error?.response?.data?.error) {
        message.error(error.response.data.error);
      } else {
        message.error('Save failed');
      }
    }
  }

  return (
    <Modal
      open={visible}
      title={isUpdate ? 'Update Item' : 'Add Item'}
      styles={modalStyles}
      centered
      onCancel={onClose}
      onOk={handleSubmit}
      destroyOnHidden
      footer={() => (
        <Form.Item>
          <button
            className="btn text-bold mr-4"
            onClick={onClose}
          >
            Cancel
          </button>
          <button
            className="btn text-bold mt-5 mb-5"
            onClick={() => handleSubmit()}
          >
            {itemToUpdate ? 'Save' : 'Add'}
          </button>
        </Form.Item>
      )}
      modalRender={(dom) => (
        <Form
          layout="vertical"
          form={form}
          name="form_in_modal"
          initialValues={{ modifier: 'public' }}
          clearOnDestroy
        >
          {dom}
        </Form>
      )}
    >
      <Space direction="vertical" size="middle" style={{ display: 'flex' }}>
        <Form.Item name="description" label="Description" rules={[{ required: true }]}>
          <Input />
        </Form.Item>
        <Form.Item name="amount" label="Amount" rules={[{ required: true }]}>
          <InputNumber style={{ width: '100%' }} />
        </Form.Item>
        <Form.Item name="category" label="Category">
          <Select allowClear options={[
            {
              label: 'General',
              value: 'general'
            },
            {
              label: 'Housing',
              value: 'housing'
            },
            {
              label: 'Food',
              value: 'food'
            },
          ]} />
        </Form.Item>
        <Form.Item name="date" label="One-off date (when not recurring)">
          <DatePicker />
        </Form.Item>

        <Form.Item name="recurring" valuePropName="checked">
          <Checkbox
            checked={recurring}
            onChange={(e) => setRecurring(e.target.checked)}
          >
            Recurring
          </Checkbox>
        </Form.Item>

        <Space direction="vertical" style={{ width: '100%' }}>
          {recurring && (

            <RecurrenceBuilder
              value={recurrence}
              onChange={setRecurrence}
              previewApiBase={apiUrl}
            />
          )}
          {additionalFields}
        </Space>
      </Space>
    </Modal>
  );
};

export default FinancialForm;
